### ISSUE TITLE
[VS Code] As a user, I want keywords to be highlighted with different colours in Java when adding JML.

### ISSUE THREAD

**Issue by pandasansgains** [utwente-fmt/vercors-ide#15]
Within the VS Code IDE when activating the extension and having a JAVA file open with valid JML annotations

Goal:

Keywords are highlighted in JAVA in all code (Including comments)
Keywords in JML can be found in [this article](https://www.openjml.org/tutorial/Expressions)

**Comment by BramOttenschot** [comment]
I was working on the injection grammer as well a bit before the weekend, and I was also thinking of injecting it into line/block comments in java, but in java, the specification language should be in /*@ ... @*/ and //@ comments, now i presume it also highlights code in /* ... */ and // comments now
