### ISSUE TITLE
Add code snippets for e.g. quantifiers 

### ISSUE THREAD

**Issue by Naum-Tomov** [utwente-fmt/vercors-ide#8]

**Comment by R-Vries** [comment]
Comments from developers:

Some basic ones (the vertical bar | indicates the cursor position):
- "/*@"  -> add closing "*/"
- "req" -> "requires |;"
- "ens" -> "ensures |;"
- "loo" -> "loop_invariant |;"
- "ass" -> "assert |;"
- "fo" -> "fold |;"
- "unf" -> "unfold |;"
- "Pe" -> "Perm(|,)"
slightly more interesting:
- "res"  ->  "resource |() = ;"
- "pur" -> "pure |() = ;"
- "\un"  ->  "\unfolding | \in "
not sure how useful it would be to have (not really adding much):
- "seq" -> "seq<|>"
- "set" -> "set<|>"
- "bag" -> "bag<|>"
those are the things that ad-hoc come to mind, I'm sure there's more
----------------------------------------------------------------------------------
/*@ @*/ for annotations in non PVL languages would be nice.
I guess recursive pure functions on a sequence often look like: pure type f(seq<type2> m) = |m| > 0 ? ... f(m.tail) : ...


with the 'for(int i=0;i++;i<n) ' example, nice to immedialy get a loop_invariant 0<=i && i<=n?
